### ISSUE TITLE
Carbon Fields 1.4 issue

### ISSUE THREAD

**Issue by Santana1053** [pkostadinov-2create/carbon-field-number#1]
Cannot make static method Carbon_Fields\\Field\\Field::admin_enqueue_scripts() non static in class Carbon_Fields\\Field\\Number_Field in /pkostadinov-2create/carbon-field-number/Number_Field.php

**Comment by pkostadinov-2create** [comment]
You should use the `namespaced` branch. For legacy reasons I would not update it into the `master` branch, since I use it as SVN external on some projects, and have no way of determine which ones.

With composer you can do:
```composer require pkostadinov-2create/carbon-field-number:dev-namespaced```
