### ISSUE TITLE
Dynamic Minumum

### ISSUE THREAD

**Issue by Santana1053** [pkostadinov-2create/carbon-field-number#3]
Is there a way that I could get a number field inside of a complex field to have a minimum value of the previous number field in that complex field group

**Comment by pkostadinov-2create** [comment]
You can code your own JS solution. Plain old jQuery would work. The number inputs would be accessible through Name attribute, with a selector that looks like:

```
#ContainerName [name^="_complex_name"][name$="[_number_field_name]"]
```

```
Container::make( 'post_meta', __( 'Container Name' ) )
	->show_on_post_type( 'post_type' )
	->add_fields( array(
		Field::make( 'complex', 'complex_name', __( 'Sample Name', 'crb' ) )
			->add_fields( array(
				Field::make( 'number', 'number_field_name', __( 'Sample Name', 'crb' ) )
			
			) ),
	) );
```
