### ISSUE TITLE
carbon 2.0 compatibility

### ISSUE THREAD

**Issue by DimaMinka** [pkostadinov-2create/carbon-field-number#6]
hi, can you please add carbon 2.0 support?

**Comment by Santana1053** [comment]
Doesn't crb 2 have this built in

**Comment by DimaMinka** [comment]
thx for your answer, u mean to use the text with special atts?
https://github.com/htmlburger/carbon-fields-docs/blob/master/documentation/20-fields/210-text.md
@Santana1053

**Comment by Santana1053** [comment]
```
Field::make( 'text', 'crb_number', 'Number Input )
    ->set_attribute( 'type', 'number' );
```
